apiVersion: v1
kind: Service
metadata:
  name: db # this must be db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  # We don't even need to specify the type because by default it's ClusterIP
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
