apiVersion: v1
kind: Service
metadata:
  name: redis # this is called as redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  # We don't even need to specify the type because by default it's ClusterIP
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
