apiVersion: v1
kind: Service
metadata:
  name: result-app # this must be result-app
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 5002
      nodePort: 30002
  selector:
    name: result-app-pod
    app: demo-voting-app
