apiVersion: v1
kind: Service
metadata:
  name: voting-app # this must be voting-app
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 5001
      nodePort: 30001
  selector:
    name: voting-app-pod
    app: demo-voting-app
